//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsSales
    {
        public int Id { get; set; }
        public System.DateTime TrxDate { get; set; }
        public string TrxDesc { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public int AsCostCenterId { get; set; }
        public int AsIncCategoryId { get; set; }
        public int AsIncClientId { get; set; }
        public string OrRef { get; set; }
    
        public virtual AsCostCenter AsCostCenter { get; set; }
        public virtual AsIncCategory AsIncCategory { get; set; }
        public virtual AsIncClient AsIncClient { get; set; }
    }
}
