//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRate
    {
        public int Id { get; set; }
        public decimal Daily { get; set; }
        public decimal Weekly { get; set; }
        public decimal Monthly { get; set; }
        public int KmFree { get; set; }
        public int KmRate { get; set; }
        public int CarUnitId { get; set; }
        public decimal OtRate { get; set; }
    
        public virtual CarUnit CarUnit { get; set; }
    }
}
