//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCarGateControl
    {
        public int Id { get; set; }
        public int InvItemId { get; set; }
        public int In_Out_flag { get; set; }
        public string Odometer { get; set; }
        public System.DateTime dtControl { get; set; }
        public string Remarks { get; set; }
        public string Driver { get; set; }
        public string Inspector { get; set; }
    
        public virtual InvItem InvItem { get; set; }
    }
}
