//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPayment
    {
        public int Id { get; set; }
        public int JobMainId { get; set; }
        public System.DateTime DtPayment { get; set; }
        public decimal PaymentAmt { get; set; }
        public string Remarks { get; set; }
        public int BankId { get; set; }
    
        public virtual JobMain JobMain { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
