//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobServicePickup
    {
        public int Id { get; set; }
        public int JobServicesId { get; set; }
        public System.DateTime JsDate { get; set; }
        public string JsTime { get; set; }
        public string JsLocation { get; set; }
        public string ClientName { get; set; }
        public string ClientContact { get; set; }
        public string ProviderName { get; set; }
        public string ProviderContact { get; set; }
    
        public virtual JobServices JobService { get; set; }
    }
}
