//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobServiceItem
    {
        public int Id { get; set; }
        public int JobServicesId { get; set; }
        public int InvItemId { get; set; }
    
        public virtual JobServices JobService { get; set; }
        public virtual InvItem InvItem { get; set; }
    }
}
