//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobType()
        {
            this.TTicket = 0;
            this.TTransport = 0;
            this.TTour = 0;
            this.THotel = 0;
            this.TOthers = 0;
        }
    
        public int Id { get; set; }
        public int JobMainId { get; set; }
        public Nullable<int> TTicket { get; set; }
        public Nullable<int> TTransport { get; set; }
        public Nullable<int> TTour { get; set; }
        public Nullable<int> THotel { get; set; }
        public Nullable<int> TOthers { get; set; }
        public string Remarks { get; set; }
    
        public virtual JobMain JobMain { get; set; }
    }
}
