//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Uom { get; set; }
        public int Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal Rate1 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
