//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesActivity
    {
        public int Id { get; set; }
        public int SalesLeadId { get; set; }
        public int SalesActCodeId { get; set; }
        public string Particulars { get; set; }
        public System.DateTime DtActivity { get; set; }
        public int SalesActStatusId { get; set; }
        public System.DateTime DtEntered { get; set; }
        public string EnteredBy { get; set; }
    
        public virtual SalesActCode SalesActCode { get; set; }
        public virtual SalesLead SalesLead { get; set; }
        public virtual SalesActStatus SalesActStatu { get; set; }
    }
}
