//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesLead()
        {
            this.SalesActivities = new HashSet<SalesActivity>();
            this.SalesLeadCategories = new HashSet<SalesLeadCategory>();
            this.SalesStatus = new HashSet<SalesStatus>();
            this.SalesLeadLinks = new HashSet<SalesLeadLink>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Details { get; set; }
        public string Remarks { get; set; }
        public int CustomerId { get; set; }
        public string CustName { get; set; }
        public System.DateTime DtEntered { get; set; }
        public string EnteredBy { get; set; }
        public decimal Price { get; set; }
        public string AssignedTo { get; set; }
        public string CustPhone { get; set; }
        public string CustEmail { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesActivity> SalesActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLeadCategory> SalesLeadCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesStatus> SalesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLeadLink> SalesLeadLinks { get; set; }
    }
}
