//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrvActionItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SrvActionItem()
        {
            this.JobActions = new HashSet<JobAction>();
        }
    
        public int Id { get; set; }
        public string Desc { get; set; }
        public string Remarks { get; set; }
        public int SortNo { get; set; }
        public int ServicesId { get; set; }
        public int SrvActionCodeId { get; set; }
    
        public virtual Services Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAction> JobActions { get; set; }
        public virtual SrvActionCode SrvActionCode { get; set; }
    }
}
